### ISSUE TITLE
all messages are 'Other'

### ISSUE THREAD

**Issue by adsick** [BlackPhlox/bevy_midi#7]
https://github.com/Boddlnagg/midir/issues/89#issue-941309769
I'm not sure, but maybe it is something wrong with my keyboard (its support on Linux).

**Comment by BlackPhlox** [comment]
The reason is that the midi-keyboard you are using does not use the standard midi NoteOn and NoteOff channel (144 and 128) but by the looks of it 156 and 140. 

I'm not an expert, but my suggestion is to look at the manual that comes with the keyboard and check if there is a setting to change the channel of the notes on the keyboard. Might be called remap or the like. Otherwise you might need to use a 3th-party midi software to map it to the correct channels. That is if you want it to work with SunVox (Guessing, haven't used SunVox before).

**Comment by BlackPhlox** [comment]
If you're out of luck with any of it, I can implement a midi channel remap override. Which would be a good feature to have nonetheless.

**Comment by adsick** [comment]
Some debug view on those 'channel' things would be nice I guess

> if there is a setting to change the channel of the notes on the keyboard. Might be called remap or the like.
there is a possibility to switch midi channel on the keyboard (1-16) but I don't think that that's what we need (mb I'm wrong)

**Comment by BlackPhlox** [comment]
Yeah, my mistake, the correct term is Midi Event Message. Though, I haven't seen many midi keyboards that can to change it.

**Comment by BlackPhlox** [comment]
@adsick If you checkout to the [adsick branch](https://github.com/BlackPhlox/bevy_midi/tree/adsick), then see if it works with the [adsick example](https://github.com/BlackPhlox/bevy_midi/blob/adsick/examples/adsick_piano.rs) that I made :)

**Comment by adsick** [comment]
I'll try

**Comment by adsick** [comment]
![image](https://user-images.githubusercontent.com/24528839/125206680-3149fd80-e291-11eb-8a49-4aaa1cccba81.png)
does it duplicating messages or smth?

**Comment by BlackPhlox** [comment]
That is most likely just a bug due to the way input is handled via threading currently. Implementing crossbeam (See issue #5) should fix it.
